-- TCL:
BEGIN TRANSACTION
UPDATE sales.customers
SET first_name = 'Omar';
SAVE TRANSACTION A

BEGIN TRANSACTION 
DELETE FROM production.brands;
SAVE TRANSACTION B

ROLLBACK TRANSACTION A;
ROLLBACK TRANSACTION B;